name: Scraping Diario + Exportar a Google Sheets

on:
  schedule:
    - cron: "0 12 * * *"  # Todos los días a las 9:00 UTC → 9:00 AM Argentina
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r scrapper/requirements.txt
          python -m playwright install

      - name: Decodificar y guardar credentials.json desde secreto en base64
        run: |
          echo "${{ secrets.GSHEET_CREDENTIALS_BASE64 }}" | base64 -d > credentials.json
      
      - name: Ver contenido del credentials.json
        run: |
          cat credentials.json

      - name: Ejecutar el scraper
        env:
          DRIVE_FOLDER_ID: ${{ vars.DRIVE_FOLDER_ID }}
          GSHEET_CREDENTIALS_PATH: credentials.json
          HEADLESS: true
        run: |
          echo "🔐 Se ejecuta el scraper con FOLDER_ID: $DRIVE_FOLDER_ID"
          python ./scrapper/run_pipeline.py --drive --debug
