name: Scraping Diario + Exportar a Google Sheets

on:
  schedule:
    - cron: "0 9 * * *"  # Todos los días a las 9:00 UTC
  workflow_dispatch:      # También te permite ejecutarlo a mano

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r scrapper/requirements.txt
          python -m playwright install

      - name: Ejecutar el scraper
        env:
          GSHEET_CREDENTIALS_JSON: ${{ secrets.GSHEET_CREDENTIALS_JSON }}
          DRIVE_FOLDER_ID: ${{ vars.DRIVE_FOLDER_ID }}
          HEADLESS: true
        run: |
          echo "🔐 Se ejecuta el scraper con FOLDER_ID: $DRIVE_FOLDER_ID"
          python ./scrapper/run_pipeline.py --drive --debug
